// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.Jenkins":       schema_pkg_apis_jenkins_v1alpha1_Jenkins(ref),
		"github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsSpec":   schema_pkg_apis_jenkins_v1alpha1_JenkinsSpec(ref),
		"github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsStatus": schema_pkg_apis_jenkins_v1alpha1_JenkinsStatus(ref),
	}
}

func schema_pkg_apis_jenkins_v1alpha1_Jenkins(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Jenkins is the Schema for the jenkins API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsStatus"),
						},
					},
				},
				Required: []string{"spec"},
			},
		},
		Dependencies: []string{
			"github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsSpec", "github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_jenkins_v1alpha1_JenkinsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "JenkinsSpec defines the desired state of Jenkins",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"persistence": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Ref:         ref("github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsPersistence"),
						},
					},
				},
				Required: []string{"persistence"},
			},
		},
		Dependencies: []string{
			"github.com/redhat-developer/openshift-jenkins-operator/pkg/apis/jenkins/v1alpha1.JenkinsPersistence"},
	}
}

func schema_pkg_apis_jenkins_v1alpha1_JenkinsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "JenkinsStatus defines the observed state of Jenkins",
				Type:        []string{"object"},
			},
		},
	}
}
